### ISSUE TITLE
OutOfRangeError (see above for traceback): End of sequence

### ISSUE THREAD

**Issue by Songxinlei** [xmeng525/RealTimeDenoisingNeuralBilateralGrid#11]
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\MCDenoising\lib\site-packages\tensorflow\python\client\session.py", line 1334, in _do_call
    return fn(*args)
  File "C:\ProgramData\Anaconda3\envs\MCDenoising\lib\site-packages\tensorflow\python\client\session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "C:\ProgramData\Anaconda3\envs\MCDenoising\lib\site-packages\tensorflow\python\client\session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.OutOfRangeError: End of sequence
	 [[{{node IteratorGetNext}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:/BGRD/RealTimeDenoisingNeuralBilateralGrid-master/network_train.py", line 176, in <module>
    feed_dict={handle_small: train_handle})
  File "C:\ProgramData\Anaconda3\envs\MCDenoising\lib\site-packages\tensorflow\python\client\session.py", line 929, in run
    run_metadata_ptr)
  File "C:\ProgramData\Anaconda3\envs\MCDenoising\lib\site-packages\tensorflow\python\client\session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\ProgramData\Anaconda3\envs\MCDenoising\lib\site-packages\tensorflow\python\client\session.py", line 1328, in _do_run
    run_metadata)
  File "C:\ProgramData\Anaconda3\envs\MCDenoising\lib\site-packages\tensorflow\python\client\session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.OutOfRangeError: End of sequence
	 [[node IteratorGetNext (defined at E:/BGRD/RealTimeDenoisingNeuralBilateralGrid-master/network_train.py:122) ]]

Caused by op 'IteratorGetNext', defined at:
  File "E:/BGRD/RealTimeDenoisingNeuralBilateralGrid-master/network_train.py", line 122, in <module>
    next_element_small = iterator_structure_small.get_next()
  File "C:\ProgramData\Anaconda3\envs\MCDenoising\lib\site-packages\tensorflow\python\data\ops\iterator_ops.py", line 414, in get_next
    output_shapes=self._structure._flat_shapes, name=name)
  File "C:\ProgramData\Anaconda3\envs\MCDenoising\lib\site-packages\tensorflow\python\ops\gen_dataset_ops.py", line 1685, in iterator_get_next
    output_shapes=output_shapes, name=name)
  File "C:\ProgramData\Anaconda3\envs\MCDenoising\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "C:\ProgramData\Anaconda3\envs\MCDenoising\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\MCDenoising\lib\site-packages\tensorflow\python\framework\ops.py", line 3300, in create_op
    op_def=op_def)
  File "C:\ProgramData\Anaconda3\envs\MCDenoising\lib\site-packages\tensorflow\python\framework\ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

OutOfRangeError (see above for traceback): End of sequence
	 [[node IteratorGetNext (defined at E:/BGRD/RealTimeDenoisingNeuralBilateralGrid-master/network_train.py:122) ]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:/BGRD/RealTimeDenoisingNeuralBilateralGrid-master/network_train.py", line 188, in <module>
    epoch_avg_psnr_train /= batch_cnt
ZeroDivisionError: float division by zero

Process finished with exit code 1

I wanted to train the network myself, but I made this mistake。

**Comment by Songxinlei** [comment]
I solved.  sorry,Tfcords are generated each time they run. But when you have the wrong path and can't read the data, the resulting tfcords are empty. So you have to delete it and run it again, or you will report an error
